package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.ModuleConfig;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.controllers.PPLTVController;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.kinematics.Odometry;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.networktables.GenericEntry;


import edu.wpi.first.units.measure.Angle;
import edu.wpi.first.units.measure.AngularVelocity;
import edu.wpi.first.units.measure.Distance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.020; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    public Pose2d red_hub = new Pose2d(11.9,4.05, new Rotation2d(0));///to be fixed
    public Pose2d blue_hub = new Pose2d(4.65,4.050,new Rotation2d(0));

    Pose2d prevPose2d = new Pose2d();


    private final ShuffleboardTab tab = Shuffleboard.getTab("DriveTrain");
    private final GenericEntry FR_drive_motorTemperatureEntry = tab.add("FR Drive Motor Temperature (C)", 0).getEntry();  
    private final GenericEntry FL_drive_motorTemperatureEntry = tab.add("FL Drive Motor Temperature (C)", 0).getEntry();
    private final GenericEntry BL_drive_motorTemperatureEntry = tab.add("BL Drive Motor Temperature (C)", 0).getEntry();
    private final GenericEntry BR_drive_motorTemperatureEntry = tab.add("BR Drive Motor Temperature (C)", 0).getEntry();

    private final GenericEntry FR_steer_motorTemperatureEntry = tab.add("FR Steer Motor Temperature (C)", 0).getEntry();    
    private final GenericEntry FL_steer_motorTemperatureEntry = tab.add("FL Steer Motor Temperature (C)", 0).getEntry();
    private final GenericEntry BL_steer_motorTemperatureEntry = tab.add("BL Steer Motor Temperature (C)", 0).getEntry();
    private final GenericEntry BR_steer_motorTemperatureEntry = tab.add("BR Steer Motor Temperature (C)", 0).getEntry();

    private final GenericEntry FR_drive_currentEntry = tab.add("FR Drive Current (A)", 0).getEntry();
    private final GenericEntry FL_drive_currentEntry = tab.add("FL Drive Current (A)", 0).getEntry();
    private final GenericEntry BL_drive_currentEntry = tab.add("BL Drive Current (A)", 0).getEntry();
    private final GenericEntry BR_drive_currentEntry = tab.add("BR Drive Current (A)", 0).getEntry();

    private final GenericEntry FR_steer_currentEntry = tab.add("FR Steer Current (A)", 0).getEntry();   
    private final GenericEntry FL_steer_currentEntry = tab.add("FL Steer Current (A)", 0).getEntry();
    private final GenericEntry BL_steer_currentEntry = tab.add("BL Steer Current (A)", 0).getEntry();
    private final GenericEntry BR_steer_currentEntry = tab.add("BR Steer Current (A)", 0).getEntry();

    private final GenericEntry FR_drive_loadRatioEntry = tab.add("FR Drive Load Ratio", 0).getEntry();
    private final GenericEntry FL_drive_loadRatioEntry = tab.add("FL Drive Load Ratio", 0).getEntry();
    private final GenericEntry BL_drive_loadRatioEntry = tab.add("BL Drive Load Ratio", 0).getEntry();
    private final GenericEntry BR_drive_loadRatioEntry = tab.add("BR Drive Load Ratio", 0).getEntry();

    private final GenericEntry chassisSpeedsEntry = tab.add("chassis speed test", 0).getEntry();

    private final GenericEntry odomentryYentry = tab.add("odemetry y",0).getEntry();
    private final GenericEntry odomentryXentry = tab.add("odemetry x",0).getEntry();
    private final GenericEntry odomentryAentry = tab.add("odemetry A",0).getEntry();

    
    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    // private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    // private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    // private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
    //     new SysIdRoutine.Config(
    //         null,        // Use default ramp rate (1 V/s)
    //         Volts.of(7), // Use dynamic voltage of 7 V
    //         null,        // Use default timeout (10 s)
    //         // Log state with SignalLogger class
    //         state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
    //     ),
    //     new SysIdRoutine.Mechanism(
    //         volts -> setControl(m_steerCharacterization.withVolts(volts)),
    //         null,
    //         this
    //     )
    // );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    // private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
    //     new SysIdRoutine.Config(
    //         /* This is in radians per second², but SysId only supports "volts per second" */
    //         Volts.of(Math.PI / 6).per(Second),
    //         /* This is in radians per second, but SysId only supports "volts" */
    //         Volts.of(Math.PI),
    //         null, // Use default timeout (10 s)
    //         // Log state with SignalLogger class
    //         state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
    //     ),
    //     new SysIdRoutine.Mechanism(
    //         output -> {
    //             /* output is actually radians per second, but SysId only supports "volts" */
    //             setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
    //             /* also log the requested output for SysId */
    //             SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
    //         },
    //         null,
    //         this
    //     )
    // );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }


    public void configure_autobuilder(){
        DCMotor defaultmotor = new DCMotor(1,1,1,1,1,1);
        ModuleConfig defaultconfig = new ModuleConfig(1, 1, 1, defaultmotor, 1, 1);
        RobotConfig config = new RobotConfig(1,1,defaultconfig, 1);
    try{
       config = RobotConfig.fromGUISettings();
    } catch (Exception e) {
      // Handle exception as needed
      e.printStackTrace();
      
    }
    
    SwerveRequest.ApplyRobotSpeeds auto_drive = new SwerveRequest.ApplyRobotSpeeds();
    
    // Configure AutoBuilder last
    AutoBuilder.configure(
            this::samplePoseNow, // Robot pose supplier
            this::resetPose, // Method to reset odometry (will be called if your auto has a starting pose)
            this::get_chasis_speeds, // ChassisSpeeds supplier. MUST BE ROBOT RELATIVE
            (speeds, feedforwards) ->{ this.applyRequest(() -> 
                auto_drive.withSpeeds(speeds)
                .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesX())
                .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesY())
            );
            }
            , // Method that will drive the robot given ROBOT RELATIVE ChassisSpeeds. Also optionally outputs individual module feedforwards
            new PPHolonomicDriveController( // PPHolonomicController is the built in path following controller for holonomic drive trains
                    new PIDConstants(5.0, 0.0, 0.0), // Translation PID constants
                    new PIDConstants(5.0, 0.0, 0.0) // Rotation PID constants
            ), // PPLTVController is the built in path following controller for differential drive trains
            config, // The robot configuration
            () -> {
            //   Boolean supplier that controls when the path will be mirrored for the red alliance
            //   This will flip the path being followed to the red side of the field.
            //   THE ORIGIN WILL REMAIN ON THE BLUE SIDE

              var alliance = DriverStation.getAlliance();
              if (alliance.isPresent()) {
                return alliance.get() == DriverStation.Alliance.Red;
              }
              return false;
            },
            this // Reference to this subsystem to set requirements
    );
    }

    ChassisSpeeds get_chasis_speeds(){
        return getKinematics().toChassisSpeeds(
            getModule(0).getCurrentState(),
            getModule(1).getCurrentState(),
            getModule(2).getCurrentState(),
            getModule(3).getCurrentState()
            );
        
    }
    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    public AngularVelocity get_rate_to_lock(){
        AngularVelocity rate = RotationsPerSecond.of(0.75);

        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        // calculate angle to hub
        
          //  distance = getpose.minus(redhub).magnitude;
        Angle offset = Degree.of(0);
        if (alliance.equals(Alliance.Blue)){

        }

            
            
        offset = get_target_angle_differnce();
        // calculate rate
        rate = rate.times(5*offset.div(-180).in(Degree));

        if (rate.gt(RotationsPerSecond.of(0.75))){
            rate = RotationsPerSecond.of(0.75);
        }
        if (rate.lt(RotationsPerSecond.of(-0.75))){
            rate = RotationsPerSecond.of(-0.75);
        }


        return rate  ;




    }


    public Angle get_target_angle_differnce(){
        //calculate the angle from the shooter to appropriately colored hub

        //var alliance = getalliancecolor();
        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        Angle angle_differnce = Degree.of(0);
        
        // Translation2d red_hub = new Translation2d((-4.249-3.041)/2.0,4.05);
        // Translation2d blue_hub = new Translation2d((4.249+3.041)/2.0,4.05);
        
        //  distance = getpose.minus(redhub).magnitude;

        // if (alliance.equals(Alliance.Blue)){
           

        // }
        Pose2d pose = samplePoseNow();

            angle_differnce = samplePoseNow().getRotation().getMeasure().minus(get_target_angle());

        return angle_differnce;
    }




    public Angle get_target_angle(){
        //calculate the angle from the shooter to appropriately colored hub

        //var alliance = getalliancecolor();
        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        Angle angle_to_target = Degree.of(0);
        
        // Translation2d red_hub = new Translation2d((-4.249-3.041)/2.0,4.05);
        // Translation2d blue_hub = new Translation2d((4.249+3.041)/2.0,4.05);
        
        //  distance = getpose.minus(redhub).magnitude;

        Pose2d pose = samplePoseNow();
        if (alliance.equals(Alliance.Blue)){

            angle_to_target = pose.relativeTo(blue_hub).getTranslation().getAngle().getMeasure().plus(Degree.of(180));
        }
        else {
            
            angle_to_target = pose.relativeTo(red_hub).getTranslation().getAngle().getMeasure().plus(Degree.of(0));
        }
   



        if (angle_to_target.in(Degree) > 180){
                angle_to_target = angle_to_target.minus(Degree.of(360));
        }
        
        return angle_to_target;
    }

    


     public Distance get_target_distance(){
          //calculate the distance from the shooter to appropriately colored hub

          //var alliance = getalliancecolor();
          Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
          Distance target_distance = Meters.of(0);
          
   

          Pose2d pose = samplePoseNow();
          if (alliance.equals(Alliance.Blue)){

             double offset = pose.relativeTo(blue_hub).getTranslation().getNorm();
             target_distance = Meters.of(offset);
             
            }
        else{
            double offset = pose.relativeTo(red_hub).getTranslation().getNorm();
            target_distance = Meters.of(offset);
        } 

          return target_distance;

        }


    public Angle get_target_moving_angle(){

        double shooter_delay = -1;
        //calculate the angle from the shooter to appropriately colored hub

        //var alliance = getalliancecolor();
        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        Angle angle_to_target = Degree.of(0);
        
        // Translation2d red_hub = new Translation2d((-4.249-3.041)/2.0,4.05);
        // Translation2d blue_hub = new Translation2d((4.249+3.041)/2.0,4.05);
        
        //  distance = getpose.minus(redhub).magnitude;

        Pose2d offset_hub = blue_hub;
        
        Transform2d speed_offset = new Transform2d(getState().Speeds.vxMetersPerSecond*shooter_delay,getState().Speeds.vxMetersPerSecond*shooter_delay,new Rotation2d(0));
        offset_hub = offset_hub.plus(speed_offset);

        if (alliance.equals(Alliance.Blue)){
           Pose2d pose = samplePoseNow();
           
           angle_to_target = pose.relativeTo(offset_hub).getTranslation().getAngle().getMeasure().plus(Degree.of(180));
        }
        else{
           
        }
            

        if (angle_to_target.in(Degree) > 180){
            angle_to_target = angle_to_target.minus(Degree.of(360));
        }   
        
        return angle_to_target;
    }

    public Distance get_target_moving_distance(){
          //calculate the distance from the shooter to appropriately colored hub

          //var alliance = getalliancecolor();
        
        Alliance alliance = DriverStation.getAlliance().orElse(Alliance.Blue);
        //   var alliance = "Blue";
        // Distance target_hub_distance = Meters.of(0);       
        double shooter_delay = -1;
    
        Pose2d offset_hub = red_hub;
        
        if (alliance.equals(Alliance.Blue)){
            offset_hub = blue_hub;
            

        }
        else{
            offset_hub = red_hub;
        }
          

        Transform2d speed_offset = new Transform2d(getState().Speeds.vxMetersPerSecond*shooter_delay,getState().Speeds.vxMetersPerSecond*shooter_delay,new Rotation2d(0));
        
        offset_hub = offset_hub.plus(speed_offset);
          
        Pose2d pose = samplePoseNow();

        double offset = pose.relativeTo(offset_hub).getTranslation().getNorm();
        
        Distance target_hub_distance = Meters.of(offset);


        return target_hub_distance;

    };

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }


    

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        FR_drive_motorTemperatureEntry.setDouble(getModule(0).getDriveMotor().getDeviceTemp().getValueAsDouble());
        FL_drive_motorTemperatureEntry.setDouble(getModule(1).getDriveMotor().getDeviceTemp().getValueAsDouble());
        BL_drive_motorTemperatureEntry.setDouble(getModule(2).getDriveMotor().getDeviceTemp().getValueAsDouble());
        BR_drive_motorTemperatureEntry.setDouble(getModule(3).getDriveMotor().getDeviceTemp().getValueAsDouble());

        FR_steer_motorTemperatureEntry.setDouble(getModule(0).getSteerMotor().getDeviceTemp().getValueAsDouble());
        FL_steer_motorTemperatureEntry.setDouble(getModule(1).getSteerMotor().getDeviceTemp().getValueAsDouble());
        BL_steer_motorTemperatureEntry.setDouble(getModule(2).getSteerMotor().getDeviceTemp().getValueAsDouble());
        BR_steer_motorTemperatureEntry.setDouble(getModule(3).getSteerMotor().getDeviceTemp().getValueAsDouble());      

        FR_drive_currentEntry.setDouble(getModule(0).getDriveMotor().getStatorCurrent().getValueAsDouble());
        FL_drive_currentEntry.setDouble(getModule(1).getDriveMotor().getStatorCurrent().getValueAsDouble());
        BL_drive_currentEntry.setDouble(getModule(2).getDriveMotor().getStatorCurrent().getValueAsDouble());
        BR_drive_currentEntry.setDouble(getModule(3).getDriveMotor().getStatorCurrent().getValueAsDouble());    

        FR_steer_currentEntry.setDouble(getModule(0).getSteerMotor().getStatorCurrent().getValueAsDouble());
        FL_steer_currentEntry.setDouble(getModule(1).getSteerMotor().getStatorCurrent().getValueAsDouble());
        BL_steer_currentEntry.setDouble(getModule(2).getSteerMotor().getStatorCurrent().getValueAsDouble());
        BR_steer_currentEntry.setDouble(getModule(3).getSteerMotor().getStatorCurrent().getValueAsDouble());    

        FR_drive_loadRatioEntry.setDouble(getModule(0).getDriveMotor().getStatorCurrent().getValueAsDouble() / getModule(0).getDriveMotor().getMotorVoltage().getValueAsDouble());
        FL_drive_loadRatioEntry.setDouble(getModule(1).getDriveMotor().getStatorCurrent().getValueAsDouble() / getModule(1).getDriveMotor().getMotorVoltage().getValueAsDouble());
        BL_drive_loadRatioEntry.setDouble(getModule(2).getDriveMotor().getStatorCurrent().getValueAsDouble() / getModule(2).getDriveMotor().getMotorVoltage().getValueAsDouble());
        BR_drive_loadRatioEntry.setDouble(getModule(3).getDriveMotor().getStatorCurrent().getValueAsDouble() / getModule(3).getDriveMotor().getMotorVoltage().getValueAsDouble());


        chassisSpeedsEntry.setDouble(this.get_chasis_speeds().vxMetersPerSecond);
        Pose2d pose = samplePoseNow();
        odomentryYentry.setDouble(pose.getY());
        odomentryXentry.setDouble(pose.getX());
        odomentryAentry.setDouble(pose.getRotation().getDegrees());
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    
    public Pose2d samplePoseNow(){
        prevPose2d = super.samplePoseAt(Utils.getCurrentTimeSeconds()).orElse(prevPose2d);
        return prevPose2d;
    }
}
